# Generated by Django 5.2.17 on 2026-09-18 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('system_prompt', models.TextField(blank=True, help_text='Global system rules shared with all players (public part).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('gateway_model', models.CharField(help_text='LiteLLM model alias, e.g. ollama/llama3.1, openai/gpt-4o, mock-echo', max_length=200)),
                ('temperature', models.FloatField(default=0.7)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('character_prompt', models.TextField(blank=True, help_text="Character description / system prompt for this player's LLM.")),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('generating', 'Generating'), ('error', 'Error')], default='idle', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='rpg.campaign')),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='rpg.modelconfig')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('campaign', 'display_name')},
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('MANUAL', 'Manual'), ('ROUND', 'Round'), ('SIMULTANEOUS', 'Simultaneous'), ('TABLE', 'Table')], default='ROUND', max_length=20)),
                ('round_order', models.JSONField(blank=True, default=list, help_text='Ordered list of Player IDs defining the round order.')),
                ('active_player_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='rpg.campaign')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('GM', 'Game Master'), ('PLAYER', 'Player'), ('SYSTEM', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE_GM_PLAYER', 'Private GM-Player'), ('GM_ONLY', 'GM only')], default='PUBLIC', max_length=20)),
                ('action_type', models.CharField(blank=True, default='', max_length=30)),
                ('private_to_gm', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rpg.campaign')),
                ('author_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='rpg.player')),
                ('private_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_messages_for', to='rpg.player')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rpg.scene')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('MANUAL', 'Manual'), ('ROUND', 'Round'), ('SIMULTANEOUS', 'Simultaneous'), ('TABLE', 'Table')], max_length=20)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('participants', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='rpg.scene')),
                ('trigger_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_turns', to='rpg.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='rpg.turn'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['scene', 'visibility'], name='rpg_message_scene_i_138471_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['private_player', 'visibility'], name='rpg_message_private_bd4d48_idx'),
        ),
    ]
